int readline(int sockd, void *vptr, int maxlen);
int writeline(int sockd, const void *vptr, int maxlen);
int trim(char* buffer);
void cleanURL(char* buffer);
int parse(char *buf, Request *req);
void reqinit(Request *req);
void initresourcepath(void);
int openresource(Request *req);
void outputheaders(int fd, Request *req);
int sendresource(int conn, int resource);
int senderror(int conn, Request* reqinfo);
void handler(int fd);
